### ISSUE TITLE
Can't write into /

### ISSUE THREAD

**Issue by hshamy24** [Chevereto/Chevereto-Free#13]
hi ...i tray to updat Chevereto-Free .. but i have this message : 
((Can't write into /app/install/update/temp/ path))

http://prntscr.com/fe0b4c

thanks

**Comment by bykidi** [comment]
Well then do chmod 777 on that folder.

**Comment by waja** [comment]
> Well then do chmod 777 on that folder.

Never do that!

**Comment by rodolfoberrios** [comment]
You need read+write in absolutely all the system if you want to use the built-in updater. That's because the system uses PHP to download the release and then it just unzips the contents of the file.

This is not an script issue at all and you should learn about filesystem permissions. WordPress has a great source of information about permissions that you should read. Here: https://codex.wordpress.org/Changing_File_Permissions

> Typically, all files should be owned by your user (ftp) account on your web server, and should be writable by that account. On shared hosts, files should never be owned by the webserver process itself (sometimes this is www, or apache, or nobody user).

Any file that needs write access from WordPress should be owned or group-owned by the user account used by the WordPress (which may be different than the server account). For example, you may have a user account that lets you FTP files back and forth to your server, but your server itself may run using a separate user, in a separate usergroup, such as dhapache or nobody. If WordPress is running as the FTP account, that account needs to have write access, i.e., be the owner of the files, or belong to a group that has write access. In the latter case, that would mean permissions are set more permissively than default (for example, 775 rather than 755 for folders, and 664 instead of 644).

Hope it helps.
