### ISSUE TITLE
404 install not found

### ISSUE THREAD

**Issue by netro** [Chevereto/Chevereto-Free#20]
Hello,
Can't install Chevereto..
Tried with web installer and unziping lastest release but "install" dir or file is missing...

Am I missing something ?

**Comment by rodolfoberrios** [comment]
You are missing something like a url rewrite module / rules. Not script issue.

**Comment by netro** [comment]
Ok fixed; missed `AllowOverride All` in vhost config..

Maybe you could add this check in the web_installer to prevent other people get the same issue ?

Thanks for help!

**Comment by rodolfoberrios** [comment]
You can't check that from PHP.

**Comment by netro** [comment]
Hum; I'm not a PHP dev but I do believe you can.
Owncloud/Nextcloud does it when you run their installer (and it's an appreciated feature);  therefore a quick check on Google seems to show it's possible too : https://stackoverflow.com/questions/9021425/how-to-check-if-mod-rewrite-is-enabled-in-php

Thanks anyway for your help :) Have a good day !

**Comment by bykidi** [comment]
as a nextcloud owner - can confirm. nextcloud installation checks for overrides when installing it

**Comment by rodolfoberrios** [comment]
In case you didn't notice, Chevereto already checks if the module is there in [app/lib/integrity-check.php](https://github.com/Chevereto/Chevereto-Free/blob/master/app/lib/integrity-check.php#L51)

Thing is that check if a module is "on" doesn't tell you if the virtual host is configured properly. 

I don't know how Nextcloud checks that stuff, I wasn't able to find any of that in the code. The thing is that PHP can't read the virtual host file so I assume that Nextcloud does some validation in the webserver layer. It won't suprise me since that system needs lots of plugs in the webserver to work with.
