### ISSUE TITLE
Image Formats (eg. Apple HEIC) and Movie/Videos ?

### ISSUE THREAD

**Issue by maltokyo** [Chevereto/Chevereto-Free#56]
iOS has for years provided capability to shoot photos in HEIC format, is there a way I can enable uploads of this format?

Also, what about movie/video uploads, would this be a possibility?  Many people shoot short movies these days on their phone and would like to share.

**Comment by rodolfoberrios** [comment]
Features you mention are not in the scope of the current version due to a self imposed limitation on the software capabilities.

The software was made to work in shared hosting, namely cPanel based servers. This was aiming for a larger user base as we didn't have $5 VPS back in 2007. To support cPanel, I had to limit what the software can do, and these limitations never went away. cPanel stuck with basically the same system and it didn't aged well for our need.

For the next major version (V4) we will ship our own server stack and eventually our own server panel. This is because we need to take control of the server infrastructure to provide a software without caps, to provide functionality soon as possible rather than when other party make it feasible.

I'm sorry if the answer is not what you could be expecting at this time, but I'm working towards a better system.
