### ISSUE TITLE
The maximum file upload size problem

### ISSUE THREAD

**Issue by conease** [chevereto/Chevereto-Free#63]
I modified PHP setting of upload_max_filesize and post_max_size at PHP.ini. And in the dashboard/settings/image-upload page, the system says:

"Maximum size allowed by server is 60 MB. This limit is capped by upload_max_filesize = 60000000 and post_max_size = 60000000 (php.ini values)."

When I change the Maximum upload file size to 60MB, it works. And the "upload_max_filesize_mb" value in "chv_settings" table also changed into "60". But a moment later, the value changes back to "2", and I cannot upload a file that large then 2MB.

 How can I configure maximum file upload size?

**Comment by rodolfoberrios** [comment]
I'm afraid that is a bug that triggers when the system tries to fix the `upload_max_filesize`, it was detected on `Chevereto 3.15.0` and it has been there since `3.0`.

Simply get rid of the highlighted code (or comment it):
https://github.com/Chevereto/Chevereto-Free/blob/master/app/loader.php#L125,L135
